'use client'

import { motion } from 'framer-motion'
import DocsLayout from '../../../components/docs/DocsLayout'
import { DocH1, DocP, DocBadge, DocH2, DocH3, DocCode, DocInfo, DocTable, DocDivider, DocCard } from '../../../components/docs/DocElements'

export default function JudgesPage() {
  return (
    <DocsLayout>
      <DocBadge color="#f59e0b">For Judges</DocBadge>
      <DocH1>Verification Guide</DocH1>
      <DocP>
        Everything you need to verify Meridian AI works as claimed.
        Three ways to verify, all under 5 minutes.
      </DocP>

      {/* Quick verification cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '12px', margin: '24px 0' }}>
        {[
          { time: '30 sec', method: 'CLI', cmd: 'pip install -e . && meridian investigate ...', color: '#10b981' },
          { time: '10 sec', method: 'Examples', cmd: 'python scripts/regenerate_examples.py', color: '#8b5cf6' },
          { time: '5 min', method: 'Full Stack', cmd: 'docker compose up -d', color: '#f59e0b' },
        ].map((v) => (
          <motion.div
            key={v.method}
            whileHover={{ y: -4, scale: 1.02 }}
            style={{
              padding: '20px',
              borderRadius: '14px',
              background: 'rgba(12, 8, 28, 0.5)',
              border: '1px solid rgba(255,255,255,0.06)',
              textAlign: 'center',
            }}
          >
            <div style={{ fontSize: '24px', fontWeight: 900, color: v.color }}>{v.time}</div>
            <div style={{ fontSize: '14px', fontWeight: 700, color: '#fff', marginTop: '4px' }}>{v.method}</div>
            <code style={{ display: 'block', marginTop: '8px', fontSize: '11px', color: 'rgba(255,255,255,0.4)', fontFamily: 'monospace' }}>
              {v.cmd}
            </code>
          </motion.div>
        ))}
      </div>

      <DocH2>Method 1: CLI (Fastest)</DocH2>
      <DocCode>{`git clone https://github.com/trueboy1123/meridian-ai
cd meridian-ai
pip install -e .
meridian investigate "urn:li:mlModel:(urn:li:dataPlatform:mlflow,churn_model_v3,PROD)"`}</DocCode>
      <DocP>
        Watch 17 workers fire, 17 DataHub mutations generated, compliance chain produced.
        All in mock mode — no dependencies needed.
      </DocP>

      <DocH2>Method 2: Examples (No Running)</DocH2>
      <DocCode>{`python scripts/regenerate_examples.py
cat examples/ai-knowledge/churn_model_v3.json
cat examples/resolution_times.json`}</DocCode>
      <DocP>
        Verify the system produces real output. All examples are generated by actual
        worker computation — not hand-written.
      </DocP>

      <DocH2>Method 3: Full Stack</DocH2>
      <DocCode>{`docker compose up -d
python scripts/seed_meridian.py
python -m backend.main`}</DocCode>
      <DocP>
        Open http://localhost:3000 (Meridian), http://localhost:9002 (DataHub),
        http://localhost:8000/docs (API).
      </DocP>

      <DocDivider />

      <DocH2>What to Look For</DocH2>
      <DocTable
        headers={['Criterion', 'Evidence', 'Where to Find It']}
        rows={[
          ['Use of DataHub', '15 capabilities (7 read + 5 write + 2 governance + Actions)', 'backend/clients/datahub_client.py'],
          ['Technical Execution', '552 tests, validation layer, maker-checker', 'tests/, backend/validation.py'],
          ['Originality', '18min → 8min → 3min flywheel, AI Knowledge panel', 'examples/resolution_times.json'],
          ['Real-World Usefulness', '$45K/day problem, 4 personas, EU AI Act', 'README.md, examples/'],
          ['Submission Quality', '7 generated examples, clear setup', 'examples/, README.md'],
        ]}
      />

      <DocDivider />

      <DocH2>The Flywheel</DocH2>
      <DocP>
        This is the most important thing to verify. Resolution time improves with
        every incident because the knowledge base compounds.
      </DocP>

      <div style={{
        padding: '24px',
        borderRadius: '14px',
        background: 'rgba(12, 8, 28, 0.5)',
        border: '1px solid rgba(255,255,255,0.06)',
        margin: '16px 0',
        fontFamily: 'monospace',
        fontSize: '14px',
        lineHeight: 2,
      }}>
        <div style={{ color: 'rgba(255,255,255,0.4)' }}>Incident #12: <span style={{ color: '#f43f5e' }}>18 min</span> (first occurrence — playbook created)</div>
        <div style={{ color: 'rgba(255,255,255,0.4)' }}>Incident #28: <span style={{ color: '#f59e0b' }}>8 min</span> (same pattern — playbook retrieved)</div>
        <div style={{ color: 'rgba(255,255,255,0.4)' }}>Incident #42: <span style={{ color: '#10b981' }}>3 min</span> (pattern matched instantly — knowledge applied)</div>
        <div style={{ marginTop: '12px', color: '#10b981', fontWeight: 700 }}>83% faster from first to third occurrence.</div>
      </div>

      <DocInfo type="tip">
        Run <code style={{ padding: '2px 6px', borderRadius: '4px', background: 'rgba(139,92,246,0.1)', color: '#c4b5fd', fontSize: '13px' }}>
        python scripts/regenerate_examples.py</code> to regenerate all examples from real worker output.
        Judges can verify by running this command.
      </DocInfo>

      <DocDivider />

      <DocH2>Key Files for Judges</DocH2>
      <DocTable
        headers={['File', 'What It Shows']}
        rows={[
          ['examples/ai-knowledge/churn_model_v3.json', 'AI Knowledge panel: resolved_incidents, health_score, confidence'],
          ['examples/resolution_times.json', 'Flywheel proof: 18min → 8min → 3min (83% improvement)'],
          ['examples/incident_42_timeline.json', 'Full investigation: 36 events, 17 workers'],
          ['examples/incident_42_summary.json', 'Summary: 17 mutations, validation_passed=true'],
          ['examples/reports/incident_042_root_cause.md', 'Generated root cause report'],
          ['examples/playbooks/schema_change_playbook.md', 'Reflexion playbook'],
          ['backend/validation.py', 'Deterministic validation layer (4 checks)'],
          ['backend/autonomy.py', '5-level progressive autonomy'],
          ['backend/workers/eu_ai_act_compliance.py', 'SHA-256 audit chain'],
          ['config/actions/meridian_auto_trigger.yaml', 'Actions Framework auto-trigger'],
        ]}
      />

      <DocDivider />

      <DocH2>Open-Source Contribution</DocH2>
      <DocP>
        Meridian contributes a DataHub Skill and an Actions Framework YAML to the
        DataHub ecosystem.
      </DocP>
      <DocTable
        headers={['Contribution', 'Location']}
        rows={[
          ['DataHub Skill', 'skill/datahub-meridian-ai/ (3 commands: investigate, health, playbook)'],
          ['Actions Framework', 'config/actions/meridian_auto_trigger.yaml'],
          ['License', 'Apache 2.0'],
        ]}
      />
    </DocsLayout>
  )
}
